version: "3.1"
services:
  product_query:
    container_name: product_query
    build: product_query
    restart: always
    ports:
      - "8765:8765"
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_PASSWORD: 1111
      MYSQL_DATABASE: svyaznoy_iphone_data


