version: "3.1"
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "80:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_PASSWORD: 1111
      MYSQL_DATABASE: svyaznoy_iphone_data


