version: "3.1"
services:
  product_query:
    container_name: product_query
    build: app
    restart: always
    ports:
      - "8765:3306"
    networks:
      - backend
  db:
    image: mysql:latest
    restart: always
    ports:
      - "80:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_PASSWORD: 1111
      MYSQL_DATABASE: svyaznoy_iphone_data


